#!/usr/bin/env python3
"""
Quick setup script for configuring OpenAI API key
Run this to create your .env file interactively
"""

import os
from pathlib import Path

def main():
    print("\n" + "="*60)
    print("  Bounty Compliance System - OpenAI Setup")
    print("="*60 + "\n")
    
    env_path = Path(__file__).parent / '.env'
    
    # Check if .env already exists
    if env_path.exists():
        print("⚠ .env file already exists!")
        response = input("Do you want to overwrite it? (yes/no): ").strip().lower()
        if response not in ['yes', 'y']:
            print("Setup cancelled.")
            return
    
    # Get API key from user
    print("\nPlease enter your OpenAI API key.")
    print("(Get one from: https://platform.openai.com/api-keys)")
    print()
    
    api_key = input("OpenAI API Key: ").strip()
    
    if not api_key:
        print("\n❌ No API key provided. Setup cancelled.")
        return
    
    if not api_key.startswith('sk-'):
        print("\n⚠ Warning: OpenAI API keys usually start with 'sk-'")
        response = input("Continue anyway? (yes/no): ").strip().lower()
        if response not in ['yes', 'y']:
            print("Setup cancelled.")
            return
    
    # Optional: Model selection
    print("\nWhich OpenAI model would you like to use?")
    print("1. gpt-4o-mini (recommended - fast and cost-effective)")
    print("2. gpt-4o (more capable but more expensive)")
    print("3. gpt-3.5-turbo (fastest and cheapest)")
    
    model_choice = input("\nEnter choice (1-3) [default: 1]: ").strip() or "1"
    
    models = {
        "1": "gpt-4o-mini",
        "2": "gpt-4o",
        "3": "gpt-3.5-turbo"
    }
    
    model = models.get(model_choice, "gpt-4o-mini")
    
    # Create .env content
    env_content = f"""# Environment variables for Bounty Compliance System
# Generated by setup_env.py

# OpenAI API Configuration
OPENAI_API_KEY={api_key}
OPENAI_MODEL={model}

# Flask Configuration
FLASK_ENV=development
FLASK_DEBUG=True
"""
    
    # Write .env file
    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        
        # Set restrictive permissions on .env file
        os.chmod(env_path, 0o600)
        
        print("\n" + "="*60)
        print("✓ Setup complete!")
        print("="*60)
        print(f"\n.env file created at: {env_path}")
        print(f"Model: {model}")
        print("\nYou can now run the application:")
        print("  python app.py")
        print("\nSecurity reminder:")
        print("  • Never commit .env to version control")
        print("  • The file is set to user-read-only permissions")
        print("  • Keep your API key secure")
        print()
        
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")
        return

if __name__ == "__main__":
    main()

